/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dsa_final_requirement;

/**
 *
 * @author joshuazabala
 */
public class Details5 extends javax.swing.JFrame {
public static String name, name2, adults, childs, stay,checkin, checkout, email, contact, r;
public static int a;
    /**
     * Creates new form Details
     */
    public Details5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel107 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        jLabel129 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        adult = new javax.swing.JSpinner();
        child = new javax.swing.JSpinner();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jLabel142 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        stays = new javax.swing.JSpinner();
        jLabel138 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel143 = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        in = new javax.swing.JTextField();
        out = new javax.swing.JTextField();
        jLabel145 = new javax.swing.JLabel();
        txtRoom = new javax.swing.JComboBox<>();
        back = new javax.swing.JButton();
        jLabel109 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(125, 90, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(1176, 865));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel107.setFont(new java.awt.Font("PT Serif", 1, 48)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(255, 255, 255));
        jLabel107.setText("MORRIS HOTEL");
        jPanel1.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 12, 375, 72));

        jPanel2.setBackground(new java.awt.Color(67, 118, 108));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 230, 230), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel127.setFont(new java.awt.Font("Kefa", 0, 30)); // NOI18N
        jLabel127.setForeground(new java.awt.Color(255, 255, 255));
        jLabel127.setText("Please fill in with your personal information");
        jPanel2.add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 17, 770, 49));

        jLabel128.setFont(new java.awt.Font("Kefa", 0, 18)); // NOI18N
        jLabel128.setForeground(new java.awt.Color(255, 255, 255));
        jLabel128.setText("First Name *");
        jPanel2.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 84, 202, 40));

        jButton2.setBackground(new java.awt.Color(177, 148, 112));
        jButton2.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Finish Booking");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 230, 230), 1, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 636, 247, 69));

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnameKeyTyped(evt);
            }
        });
        jPanel2.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 130, 400, 38));

        lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lnameKeyTyped(evt);
            }
        });
        jPanel2.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 130, 400, 38));

        jLabel129.setFont(new java.awt.Font("Kefa", 0, 18)); // NOI18N
        jLabel129.setForeground(new java.awt.Color(255, 255, 255));
        jLabel129.setText("Last Name *");
        jPanel2.add(jLabel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 84, 202, 40));

        jPanel3.setBackground(new java.awt.Color(125, 90, 80));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 717, 883, -1));

        jPanel4.setBackground(new java.awt.Color(125, 90, 80));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 616, 883, -1));

        jLabel130.setFont(new java.awt.Font("Kefa", 0, 18)); // NOI18N
        jLabel130.setForeground(new java.awt.Color(255, 255, 255));
        jLabel130.setText("Number of Adults *");
        jPanel2.add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 186, 202, 40));

        jLabel131.setFont(new java.awt.Font("Kefa", 0, 18)); // NOI18N
        jLabel131.setForeground(new java.awt.Color(255, 255, 255));
        jLabel131.setText("Number of Child *");
        jPanel2.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 186, 202, 40));

        adult.setModel(new javax.swing.SpinnerNumberModel(0, 0, 7, 1));
        jPanel2.add(adult, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 232, 400, 38));

        child.setModel(new javax.swing.SpinnerNumberModel(0, 0, 7, 1));
        jPanel2.add(child, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 232, 400, 38));

        jLabel132.setFont(new java.awt.Font("Kefa", 0, 18)); // NOI18N
        jLabel132.setForeground(new java.awt.Color(255, 255, 255));
        jLabel132.setText("Number of Days Staying*");
        jPanel2.add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 288, 230, 40));

        jLabel133.setFont(new java.awt.Font("Kefa", 0, 18)); // NOI18N
        jLabel133.setForeground(new java.awt.Color(255, 255, 255));
        jLabel133.setText("Check In Date*");
        jPanel2.add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 288, -1, 40));

        jLabel134.setFont(new java.awt.Font("Kefa", 0, 18)); // NOI18N
        jLabel134.setForeground(new java.awt.Color(255, 255, 255));
        jLabel134.setText("Room*");
        jPanel2.add(jLabel134, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 391, -1, 40));

        jLabel135.setFont(new java.awt.Font("Kefa", 0, 18)); // NOI18N
        jLabel135.setForeground(new java.awt.Color(255, 255, 255));
        jLabel135.setText("Email*");
        jPanel2.add(jLabel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 391, 230, 40));
        jPanel2.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 443, 509, 40));

        jLabel142.setFont(new java.awt.Font("Kefa", 0, 12)); // NOI18N
        jLabel142.setForeground(new java.awt.Color(255, 255, 255));
        jLabel142.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel142.setText("Please take note that email is required in this section so that we contact you if problem arise");
        jPanel2.add(jLabel142, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 489, 764, -1));

        jLabel136.setFont(new java.awt.Font("Kefa", 0, 18)); // NOI18N
        jLabel136.setForeground(new java.awt.Color(255, 255, 255));
        jLabel136.setText("Contact Number*");
        jPanel2.add(jLabel136, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 510, 230, 40));

        jLabel137.setFont(new java.awt.Font("Kefa", 0, 18)); // NOI18N
        jLabel137.setForeground(new java.awt.Color(255, 255, 255));
        jLabel137.setText("+63");
        jPanel2.add(jLabel137, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 43, 40));

        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });
        number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numberKeyTyped(evt);
            }
        });
        jPanel2.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 567, 331, -1));

        stays.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        jPanel2.add(stays, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 334, 338, 38));

        jLabel138.setFont(new java.awt.Font("Kefa", 0, 12)); // NOI18N
        jLabel138.setForeground(new java.awt.Color(255, 255, 255));
        jLabel138.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel138.setText("Day");
        jPanel2.add(jLabel138, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 375, 50, -1));

        jLabel139.setFont(new java.awt.Font("Kefa", 0, 12)); // NOI18N
        jLabel139.setForeground(new java.awt.Color(255, 255, 255));
        jLabel139.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel139.setText("Year");
        jPanel2.add(jLabel139, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 375, 72, -1));

        jLabel140.setFont(new java.awt.Font("Kefa", 0, 12)); // NOI18N
        jLabel140.setForeground(new java.awt.Color(255, 255, 255));
        jLabel140.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel140.setText("Month");
        jPanel2.add(jLabel140, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 375, 72, -1));

        jLabel141.setFont(new java.awt.Font("Kefa", 0, 12)); // NOI18N
        jLabel141.setForeground(new java.awt.Color(255, 255, 255));
        jLabel141.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel141.setText("Day");
        jPanel2.add(jLabel141, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 375, 44, -1));

        jLabel143.setFont(new java.awt.Font("Kefa", 0, 12)); // NOI18N
        jLabel143.setForeground(new java.awt.Color(255, 255, 255));
        jLabel143.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel143.setText("Month");
        jPanel2.add(jLabel143, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 375, 72, -1));

        jLabel144.setFont(new java.awt.Font("Kefa", 0, 12)); // NOI18N
        jLabel144.setForeground(new java.awt.Color(255, 255, 255));
        jLabel144.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel144.setText("Year");
        jPanel2.add(jLabel144, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 375, 72, -1));

        in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inActionPerformed(evt);
            }
        });
        in.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inKeyTyped(evt);
            }
        });
        jPanel2.add(in, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 334, 200, 35));

        out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outActionPerformed(evt);
            }
        });
        out.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                outKeyTyped(evt);
            }
        });
        jPanel2.add(out, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 334, 200, 35));

        jLabel145.setFont(new java.awt.Font("Kefa", 0, 18)); // NOI18N
        jLabel145.setForeground(new java.awt.Color(255, 255, 255));
        jLabel145.setText("Check Out Date*");
        jPanel2.add(jLabel145, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 298, -1, 40));

        txtRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deluxe Room", "Single Standard Room", "Standard Room", "Family Room", "Barkada Room" }));
        txtRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomActionPerformed(evt);
            }
        });
        jPanel2.add(txtRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 443, 240, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, 755));

        back.setBackground(new java.awt.Color(177, 148, 112));
        back.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        back.setText("Go Back Home");
        back.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 155, 38));

        jLabel109.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
        jLabel109.setText("2");
        jPanel1.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 24, -1, 46));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 42, -1, -1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 41, -1, -1));

        jLabel110.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
        jLabel110.setForeground(new java.awt.Color(255, 255, 255));
        jLabel110.setText("3");
        jPanel1.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 24, -1, 46));

        jLabel111.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
        jLabel111.setForeground(new java.awt.Color(255, 255, 255));
        jLabel111.setText("1");
        jPanel1.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 24, -1, 46));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1007, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           
        
            // TODO add your handling code here:
            name = fname.getText();
            name2 = lname.getText();
            adults = adult.getValue().toString();
            a = Integer.parseInt(adults);
            childs = child.getValue().toString();
            stay = stays.getValue().toString();
            checkin = in.getText();
            checkout = out.getText();
            email = mail.getText();
            contact = number.getText();
            r = txtRoom.getSelectedItem().toString();

            
      if (name.isEmpty()||name2.isEmpty()||checkin.isEmpty()||checkout.isEmpty()||email.isEmpty()||contact.isEmpty()) {
            jOptionPane1.showMessageDialog(this, "Please input complete details!");
           } else if(a<1){
                jOptionPane1.showMessageDialog(this, "There's no adult, reservation failed");
            } else {
                int yes_no = jOptionPane1.showConfirmDialog(this, "Do you want to finish booking?", "Confirm",jOptionPane1.YES_NO_OPTION);

             if (yes_no==jOptionPane1.YES_OPTION) {
                   Summary6 tails = new Summary6();
                   tails.show();
                   dispose();
            }
        
            

                
                
           }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void fnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyTyped
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_fnameKeyTyped

    private void lnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnameKeyTyped
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_lnameKeyTyped

    private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberActionPerformed

    private void numberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_numberKeyTyped

    private void inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inActionPerformed

    private void inKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_inKeyTyped

    private void outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outActionPerformed

    private void outKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_outKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_outKeyTyped

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Rooms4 room = new Rooms4();
        room.show();
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void txtRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Details5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner adult;
    private javax.swing.JButton back;
    private javax.swing.JSpinner child;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField in;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField number;
    private javax.swing.JTextField out;
    private javax.swing.JSpinner stays;
    private javax.swing.JComboBox<String> txtRoom;
    // End of variables declaration//GEN-END:variables
}
